#pragma once

#include <vector>
#include <cstdint>
#include "graph.hpp"

namespace crp {

// A lightweight overlay edge with single weight (distance or time)
struct OverlayEdge {
    NodeId target;
    float  weight;
};

// Overlay graph corresponding to cell boundaries generated by CRP preprocessing.
class OverlayGraph {
public:
    // Load pre-processed overlay from a binary mmap-able file (placeholder)
    void load(const char* /*path*/) {
        // TODO: mmap overlay file into offsets_ & edges_
    }

    [[nodiscard]] size_t num_nodes() const { return offsets_.empty() ? 0 : offsets_.size() - 1; }

    auto neighbors(NodeId u) const {
        return std::make_pair(edges_.begin() + offsets_[u], edges_.begin() + offsets_[u + 1]);
    }

private:
    std::vector<uint32_t> offsets_;
    std::vector<OverlayEdge> edges_;
};

} // namespace crp